=== BloodyDawn/Ertheia/Data/game/data/xsd/CharTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:element name="list" type="listType"/>
		<xs:complexType name="listType">
				<xs:sequence>
						<xs:element type="classtemplateType" name="classtemplate"/>
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="classtemplateType">
				<xs:sequence>
						<xs:element type="lvlupvaluesType" name="lvlupvalues"/>
				</xs:sequence>
				<xs:attribute type="xs:string" name="name"/>
				<xs:attribute type="xs:string" name="serverName"/>
				<xs:attribute type="xs:string" name="classId"/>
				<xs:attribute type="xs:string" name="parentClassId"/>
				<xs:attribute type="xs:string" name="classLevel"/>
				<xs:attribute type="xs:string" name="raceId"/>
		</xs:complexType>
		<xs:complexType name="lvlupvaluesType">
				<xs:sequence>
						<xs:element type="lvl_addType" name="lvl_add" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="lvl_addType">
				<xs:simpleContent>
						<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="lvl" use="optional"/>
								<xs:attribute type="xs:string" name="hp" use="optional"/>
								<xs:attribute type="xs:string" name="mp" use="optional"/>
								<xs:attribute type="xs:string" name="cp" use="optional"/>
						</xs:extension>
				</xs:simpleContent>
		</xs:complexType>
</xs:schema>

=== BloodyDawn/Ertheia/Data/game/data/stats/player/class_data/[167]Feoh Wizard Soultaker.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/CharTemplates.xsd">
	<classtemplate classId="167" classLevel="85" name="Волшебник Фео" parentClassId="95" raceId="0" serverName="FeohWizard_Soultaker">
		<lvlupvalues>
			<lvl_add cp="50.5" hp="101.0" lvl="1" mp="40.0"/>
			<lvl_add cp="58.235" hp="116.47" lvl="2" mp="47.28"/>
			<lvl_add cp="66.055" hp="132.11" lvl="3" mp="54.64"/>
			<lvl_add cp="73.96" hp="147.92" lvl="4" mp="62.08"/>
			<lvl_add cp="81.95" hp="163.9" lvl="5" mp="69.6"/>
			<lvl_add cp="90.025" hp="180.05" lvl="6" mp="77.2"/>
			<lvl_add cp="98.185" hp="196.37" lvl="7" mp="84.88"/>
			<lvl_add cp="106.43" hp="212.86" lvl="8" mp="92.64"/>
			<lvl_add cp="114.76" hp="229.52" lvl="9" mp="100.48"/>
			<lvl_add cp="123.175" hp="246.35" lvl="10" mp="108.4"/>
			<lvl_add cp="131.675" hp="263.35" lvl="11" mp="116.4"/>
			<lvl_add cp="140.26" hp="280.52" lvl="12" mp="124.48"/>
			<lvl_add cp="148.93" hp="297.86" lvl="13" mp="132.64"/>
			<lvl_add cp="157.685" hp="315.37" lvl="14" mp="140.88"/>
			<lvl_add cp="166.525" hp="333.05" lvl="15" mp="149.2"/>
			<lvl_add cp="175.45" hp="350.9" lvl="16" mp="157.6"/>
			<lvl_add cp="184.46" hp="368.92" lvl="17" mp="166.08"/>
			<lvl_add cp="193.555" hp="387.11" lvl="18" mp="174.64"/>
			<lvl_add cp="202.735" hp="405.47" lvl="19" mp="183.28"/>
			<lvl_add cp="212.0" hp="424.0" lvl="20" mp="192.0"/>
			<lvl_add cp="225.75" hp="451.5" lvl="21" mp="205.2"/>
			<lvl_add cp="239.625" hp="479.25" lvl="22" mp="218.52"/>
			<lvl_add cp="253.625" hp="507.25" lvl="23" mp="231.96"/>
			<lvl_add cp="267.75" hp="535.5" lvl="24" mp="245.52"/>
			<lvl_add cp="282.0" hp="564.0" lvl="25" mp="259.2"/>
			<lvl_add cp="296.375" hp="592.75" lvl="26" mp="273.0"/>
			<lvl_add cp="310.875" hp="621.75" lvl="27" mp="286.92"/>
			<lvl_add cp="325.5" hp="651.0" lvl="28" mp="300.96"/>
			<lvl_add cp="340.25" hp="680.5" lvl="29" mp="315.12"/>
			<lvl_add cp="355.125" hp="710.25" lvl="30" mp="329.4"/>
			<lvl_add cp="370.125" hp="740.25" lvl="31" mp="343.8"/>
			<lvl_add cp="385.25" hp="770.5" lvl="32" mp="358.32"/>
			<lvl_add cp="400.5" hp="801.0" lvl="33" mp="372.96"/>
			<lvl_add cp="415.875" hp="831.75" lvl="34" mp="387.72"/>
			<lvl_add cp="431.375" hp="862.75" lvl="35" mp="402.6"/>
			<lvl_add cp="447.0" hp="894.0" lvl="36" mp="417.6"/>
			<lvl_add cp="462.75" hp="925.5" lvl="37" mp="432.72"/>
			<lvl_add cp="478.625" hp="957.25" lvl="38" mp="447.96"/>
			<lvl_add cp="494.625" hp="989.25" lvl="39" mp="463.32"/>
			<lvl_add cp="510.75" hp="1021.5" lvl="40" mp="478.8"/>
			<lvl_add cp="533.5" hp="1067.0" lvl="41" mp="504.8"/>
			<lvl_add cp="556.425" hp="1112.85" lvl="42" mp="531.0"/>
			<lvl_add cp="579.525" hp="1159.05" lvl="43" mp="557.4"/>
			<lvl_add cp="602.8" hp="1205.6" lvl="44" mp="584.0"/>
			<lvl_add cp="626.25" hp="1252.5" lvl="45" mp="610.8"/>
			<lvl_add cp="649.875" hp="1299.75" lvl="46" mp="637.8"/>
			<lvl_add cp="673.675" hp="1347.35" lvl="47" mp="665.0"/>
			<lvl_add cp="697.65" hp="1395.3" lvl="48" mp="692.4"/>
			<lvl_add cp="721.8" hp="1443.6" lvl="49" mp="720.0"/>
			<lvl_add cp="746.125" hp="1492.25" lvl="50" mp="747.8"/>
			<lvl_add cp="770.625" hp="1541.25" lvl="51" mp="775.8"/>
			<lvl_add cp="795.3" hp="1590.6" lvl="52" mp="804.0"/>
			<lvl_add cp="820.15" hp="1640.3" lvl="53" mp="832.4"/>
			<lvl_add cp="845.175" hp="1690.35" lvl="54" mp="861.0"/>
			<lvl_add cp="870.375" hp="1740.75" lvl="55" mp="889.8"/>
			<lvl_add cp="895.75" hp="1791.5" lvl="56" mp="918.8"/>
			<lvl_add cp="921.3" hp="1842.6" lvl="57" mp="948.0"/>
			<lvl_add cp="947.025" hp="1894.05" lvl="58" mp="977.4"/>
			<lvl_add cp="972.925" hp="1945.85" lvl="59" mp="1007.0"/>
			<lvl_add cp="999.0" hp="1998.0" lvl="60" mp="1036.8"/>
			<lvl_add cp="1025.25" hp="2050.5" lvl="61" mp="1066.8"/>
			<lvl_add cp="1051.675" hp="2103.35" lvl="62" mp="1097.0"/>
			<lvl_add cp="1078.275" hp="2156.55" lvl="63" mp="1127.4"/>
			<lvl_add cp="1105.05" hp="2210.1" lvl="64" mp="1158.0"/>
			<lvl_add cp="1132.0" hp="2264.0" lvl="65" mp="1188.8"/>
			<lvl_add cp="1159.125" hp="2318.25" lvl="66" mp="1219.8"/>
			<lvl_add cp="1186.425" hp="2372.85" lvl="67" mp="1251.0"/>
			<lvl_add cp="1213.9" hp="2427.8" lvl="68" mp="1282.4"/>
			<lvl_add cp="1241.55" hp="2483.1" lvl="69" mp="1314.0"/>
			<lvl_add cp="1269.375" hp="2538.75" lvl="70" mp="1345.8"/>
			<lvl_add cp="1297.375" hp="2594.75" lvl="71" mp="1377.8"/>
			<lvl_add cp="1325.55" hp="2651.1" lvl="72" mp="1410.0"/>
			<lvl_add cp="1353.9" hp="2707.8" lvl="73" mp="1442.4"/>
			<lvl_add cp="1382.425" hp="2764.85" lvl="74" mp="1475.0"/>
			<lvl_add cp="1411.125" hp="2822.25" lvl="75" mp="1507.8"/>
			<lvl_add cp="1440.0" hp="2880.0" lvl="76" mp="1540.8"/>
			<lvl_add cp="1469.05" hp="2938.1" lvl="77" mp="1574.0"/>
			<lvl_add cp="1498.275" hp="2996.55" lvl="78" mp="1607.4"/>
			<lvl_add cp="1527.675" hp="3055.35" lvl="79" mp="1641.0"/>
			<lvl_add cp="1557.25" hp="3114.5" lvl="80" mp="1674.8"/>
			<lvl_add cp="1587.0" hp="3174.0" lvl="81" mp="1708.8"/>
			<lvl_add cp="1616.925" hp="3233.85" lvl="82" mp="1743.0"/>
			<lvl_add cp="1647.025" hp="3294.05" lvl="83" mp="1777.4"/>
			<lvl_add cp="1677.3" hp="3354.6" lvl="84" mp="1812.0"/>
			<lvl_add cp="9596.88" hp="6950.2" lvl="85" mp="2770.2"/>
			<lvl_add cp="9690.97" hp="7018.34" lvl="86" mp="2822.7"/>
			<lvl_add cp="9785.98" hp="7087.15" lvl="87" mp="2875.5"/>
			<lvl_add cp="9881.92" hp="7156.63" lvl="88" mp="2928.6"/>
			<lvl_add cp="9978.8" hp="7226.8" lvl="89" mp="2982.0"/>
			<lvl_add cp="10076.64" hp="7297.65" lvl="90" mp="3035.7"/>
			<lvl_add cp="10175.43" hp="7369.19" lvl="91" mp="3089.7"/>
			<lvl_add cp="10275.18" hp="7441.44" lvl="92" mp="3144.0"/>
			<lvl_add cp="10375.92" hp="7514.4" lvl="93" mp="3198.6"/>
			<lvl_add cp="10477.65" hp="7588.07" lvl="94" mp="3253.5"/>
			<lvl_add cp="10580.37" hp="7662.46" lvl="95" mp="3308.7"/>
			<lvl_add cp="10684.1" hp="7737.58" lvl="96" mp="3364.2"/>
			<lvl_add cp="10788.84" hp="7813.44" lvl="97" mp="3420.0"/>
			<lvl_add cp="10894.62" hp="7890.04" lvl="98" mp="3476.1"/>
			<lvl_add cp="11001.43" hp="7967.39" lvl="99" mp="3532.5"/>
		</lvlupvalues>
	</classtemplate>
</list>
