=== BloodyDawn/Ertheia/Data/game/data/xsd/CharTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:element name="list" type="listType"/>
		<xs:complexType name="listType">
				<xs:sequence>
						<xs:element type="classtemplateType" name="classtemplate"/>
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="classtemplateType">
				<xs:sequence>
						<xs:element type="lvlupvaluesType" name="lvlupvalues"/>
				</xs:sequence>
				<xs:attribute type="xs:string" name="name"/>
				<xs:attribute type="xs:string" name="serverName"/>
				<xs:attribute type="xs:string" name="classId"/>
				<xs:attribute type="xs:string" name="parentClassId"/>
				<xs:attribute type="xs:string" name="classLevel"/>
				<xs:attribute type="xs:string" name="raceId"/>
		</xs:complexType>
		<xs:complexType name="lvlupvaluesType">
				<xs:sequence>
						<xs:element type="lvl_addType" name="lvl_add" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="lvl_addType">
				<xs:simpleContent>
						<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="lvl" use="optional"/>
								<xs:attribute type="xs:string" name="hp" use="optional"/>
								<xs:attribute type="xs:string" name="mp" use="optional"/>
								<xs:attribute type="xs:string" name="cp" use="optional"/>
						</xs:extension>
				</xs:simpleContent>
		</xs:complexType>
</xs:schema>

=== BloodyDawn/Ertheia/Data/game/data/stats/player/class_data/[124]Female Soldier.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/CharTemplates.xsd">
	<classtemplate classId="124" classLevel="1" name="Грешница" raceId="5" serverName="kamael_f_soldier">
		<lvlupvalues>
			<lvl_add cp="48.5" hp="97.0" lvl="1" mp="40.0"/>
			<lvl_add cp="56.69" hp="113.38" lvl="2" mp="47.28"/>
			<lvl_add cp="64.97" hp="129.94" lvl="3" mp="54.64"/>
			<lvl_add cp="73.34" hp="146.68" lvl="4" mp="62.08"/>
			<lvl_add cp="81.8" hp="163.6" lvl="5" mp="69.6"/>
			<lvl_add cp="90.35" hp="180.7" lvl="6" mp="77.2"/>
			<lvl_add cp="98.99" hp="197.98" lvl="7" mp="84.88"/>
			<lvl_add cp="107.72" hp="215.44" lvl="8" mp="92.64"/>
			<lvl_add cp="116.54" hp="233.08" lvl="9" mp="100.48"/>
			<lvl_add cp="125.45" hp="250.9" lvl="10" mp="108.4"/>
			<lvl_add cp="134.45" hp="268.9" lvl="11" mp="116.4"/>
			<lvl_add cp="143.54" hp="287.08" lvl="12" mp="124.48"/>
			<lvl_add cp="152.72" hp="305.44" lvl="13" mp="132.64"/>
			<lvl_add cp="161.99" hp="323.98" lvl="14" mp="140.88"/>
			<lvl_add cp="171.35" hp="342.7" lvl="15" mp="149.2"/>
			<lvl_add cp="180.8" hp="361.6" lvl="16" mp="157.6"/>
			<lvl_add cp="190.34" hp="380.68" lvl="17" mp="166.08"/>
			<lvl_add cp="199.97" hp="399.94" lvl="18" mp="174.64"/>
			<lvl_add cp="209.69" hp="419.38" lvl="19" mp="183.28"/>
			<lvl_add cp="219.5" hp="439.0" lvl="20" mp="192.0"/>
			<lvl_add cp="229.4" hp="458.8" lvl="21" mp="200.8"/>
			<lvl_add cp="239.39" hp="478.78" lvl="22" mp="209.68"/>
			<lvl_add cp="249.47" hp="498.94" lvl="23" mp="218.64"/>
			<lvl_add cp="259.64" hp="519.28" lvl="24" mp="227.68"/>
			<lvl_add cp="269.9" hp="539.8" lvl="25" mp="236.8"/>
			<lvl_add cp="280.25" hp="560.5" lvl="26" mp="246.0"/>
			<lvl_add cp="290.69" hp="581.38" lvl="27" mp="255.28"/>
			<lvl_add cp="301.22" hp="602.44" lvl="28" mp="264.64"/>
			<lvl_add cp="311.84" hp="623.68" lvl="29" mp="274.08"/>
			<lvl_add cp="322.55" hp="645.1" lvl="30" mp="283.6"/>
			<lvl_add cp="333.35" hp="666.7" lvl="31" mp="293.2"/>
			<lvl_add cp="344.24" hp="688.48" lvl="32" mp="302.88"/>
			<lvl_add cp="355.22" hp="710.44" lvl="33" mp="312.64"/>
			<lvl_add cp="366.29" hp="732.58" lvl="34" mp="322.48"/>
			<lvl_add cp="377.45" hp="754.9" lvl="35" mp="332.4"/>
			<lvl_add cp="388.7" hp="777.4" lvl="36" mp="342.4"/>
			<lvl_add cp="400.04" hp="800.08" lvl="37" mp="352.48"/>
			<lvl_add cp="411.47" hp="822.94" lvl="38" mp="362.64"/>
			<lvl_add cp="422.99" hp="845.98" lvl="39" mp="372.88"/>
			<lvl_add cp="434.6" hp="869.2" lvl="40" mp="383.2"/>
			<lvl_add cp="446.3" hp="892.6" lvl="41" mp="393.6"/>
			<lvl_add cp="458.09" hp="916.18" lvl="42" mp="404.08"/>
			<lvl_add cp="469.97" hp="939.94" lvl="43" mp="414.64"/>
			<lvl_add cp="481.94" hp="963.88" lvl="44" mp="425.28"/>
			<lvl_add cp="494.0" hp="988.0" lvl="45" mp="436.0"/>
			<lvl_add cp="506.15" hp="1012.3" lvl="46" mp="446.8"/>
			<lvl_add cp="518.39" hp="1036.78" lvl="47" mp="457.68"/>
			<lvl_add cp="530.72" hp="1061.44" lvl="48" mp="468.64"/>
			<lvl_add cp="543.14" hp="1086.28" lvl="49" mp="479.68"/>
			<lvl_add cp="555.65" hp="1111.3" lvl="50" mp="490.8"/>
			<lvl_add cp="568.25" hp="1136.5" lvl="51" mp="502.0"/>
			<lvl_add cp="580.94" hp="1161.88" lvl="52" mp="513.28"/>
			<lvl_add cp="593.72" hp="1187.44" lvl="53" mp="524.64"/>
			<lvl_add cp="606.59" hp="1213.18" lvl="54" mp="536.08"/>
			<lvl_add cp="619.55" hp="1239.1" lvl="55" mp="547.6"/>
			<lvl_add cp="632.6" hp="1265.2" lvl="56" mp="559.2"/>
			<lvl_add cp="645.74" hp="1291.48" lvl="57" mp="570.88"/>
			<lvl_add cp="658.97" hp="1317.94" lvl="58" mp="582.64"/>
			<lvl_add cp="672.29" hp="1344.58" lvl="59" mp="594.48"/>
			<lvl_add cp="685.7" hp="1371.4" lvl="60" mp="606.4"/>
			<lvl_add cp="699.2" hp="1398.4" lvl="61" mp="618.4"/>
			<lvl_add cp="712.79" hp="1425.58" lvl="62" mp="630.48"/>
			<lvl_add cp="726.47" hp="1452.94" lvl="63" mp="642.64"/>
			<lvl_add cp="740.24" hp="1480.48" lvl="64" mp="654.88"/>
			<lvl_add cp="754.1" hp="1508.2" lvl="65" mp="667.2"/>
			<lvl_add cp="768.05" hp="1536.1" lvl="66" mp="679.6"/>
			<lvl_add cp="782.09" hp="1564.18" lvl="67" mp="692.08"/>
			<lvl_add cp="796.22" hp="1592.44" lvl="68" mp="704.64"/>
			<lvl_add cp="810.44" hp="1620.88" lvl="69" mp="717.28"/>
			<lvl_add cp="824.75" hp="1649.5" lvl="70" mp="730.0"/>
			<lvl_add cp="839.15" hp="1678.3" lvl="71" mp="742.8"/>
			<lvl_add cp="853.64" hp="1707.28" lvl="72" mp="755.68"/>
			<lvl_add cp="868.22" hp="1736.44" lvl="73" mp="768.64"/>
			<lvl_add cp="882.89" hp="1765.78" lvl="74" mp="781.68"/>
			<lvl_add cp="897.65" hp="1795.3" lvl="75" mp="794.8"/>
			<lvl_add cp="912.5" hp="1825.0" lvl="76" mp="808.0"/>
			<lvl_add cp="927.44" hp="1854.88" lvl="77" mp="821.28"/>
			<lvl_add cp="942.47" hp="1884.94" lvl="78" mp="834.64"/>
			<lvl_add cp="957.59" hp="1915.18" lvl="79" mp="848.08"/>
			<lvl_add cp="972.8" hp="1945.6" lvl="80" mp="861.6"/>
			<lvl_add cp="988.1" hp="1976.2" lvl="81" mp="875.2"/>
			<lvl_add cp="1003.49" hp="2006.98" lvl="82" mp="888.88"/>
			<lvl_add cp="1018.97" hp="2037.94" lvl="83" mp="902.64"/>
			<lvl_add cp="1034.54" hp="2069.08" lvl="84" mp="916.48"/>
			<lvl_add cp="1050.2" hp="2100.4" lvl="85" mp="930.4"/>
			<lvl_add cp="1065.95" hp="2131.9" lvl="86" mp="944.4"/>
			<lvl_add cp="1081.79" hp="2163.58" lvl="87" mp="958.48"/>
			<lvl_add cp="1097.72" hp="2195.44" lvl="88" mp="972.64"/>
			<lvl_add cp="1113.74" hp="2227.48" lvl="89" mp="986.88"/>
			<lvl_add cp="1129.85" hp="2259.7" lvl="90" mp="1001.2"/>
			<lvl_add cp="1146.05" hp="2292.1" lvl="91" mp="1015.6"/>
			<lvl_add cp="1162.34" hp="2324.68" lvl="92" mp="1030.08"/>
			<lvl_add cp="1178.72" hp="2357.44" lvl="93" mp="1044.64"/>
			<lvl_add cp="1195.19" hp="2390.38" lvl="94" mp="1059.28"/>
			<lvl_add cp="1211.75" hp="2423.5" lvl="95" mp="1074.0"/>
			<lvl_add cp="1228.4" hp="2456.8" lvl="96" mp="1088.8"/>
			<lvl_add cp="1245.14" hp="2490.28" lvl="97" mp="1103.68"/>
			<lvl_add cp="1261.97" hp="2523.94" lvl="98" mp="1118.64"/>
			<lvl_add cp="1278.89" hp="2557.78" lvl="99" mp="1133.68"/>
		</lvlupvalues>
	</classtemplate>
</list>

=== BloodyDawn/Ertheia/Data/game/data/stats/player/class_data/[015]Cleric.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/CharTemplates.xsd">
	<classtemplate classId="15" classLevel="20" name="Клерик" parentClassId="10" raceId="0" serverName="cleric">
		<lvlupvalues>
			<lvl_add cp="50.5" hp="101.0" lvl="1" mp="40.0"/>
			<lvl_add cp="58.235" hp="116.47" lvl="2" mp="47.28"/>
			<lvl_add cp="66.055" hp="132.11" lvl="3" mp="54.64"/>
			<lvl_add cp="73.96" hp="147.92" lvl="4" mp="62.08"/>
			<lvl_add cp="81.95" hp="163.9" lvl="5" mp="69.6"/>
			<lvl_add cp="90.025" hp="180.05" lvl="6" mp="77.2"/>
			<lvl_add cp="98.185" hp="196.37" lvl="7" mp="84.88"/>
			<lvl_add cp="106.43" hp="212.86" lvl="8" mp="92.64"/>
			<lvl_add cp="114.76" hp="229.52" lvl="9" mp="100.48"/>
			<lvl_add cp="123.175" hp="246.35" lvl="10" mp="108.4"/>
			<lvl_add cp="131.675" hp="263.35" lvl="11" mp="116.4"/>
			<lvl_add cp="140.26" hp="280.52" lvl="12" mp="124.48"/>
			<lvl_add cp="148.93" hp="297.86" lvl="13" mp="132.64"/>
			<lvl_add cp="157.685" hp="315.37" lvl="14" mp="140.88"/>
			<lvl_add cp="166.525" hp="333.05" lvl="15" mp="149.2"/>
			<lvl_add cp="175.45" hp="350.9" lvl="16" mp="157.6"/>
			<lvl_add cp="184.46" hp="368.92" lvl="17" mp="166.08"/>
			<lvl_add cp="193.555" hp="387.11" lvl="18" mp="174.64"/>
			<lvl_add cp="202.735" hp="405.47" lvl="19" mp="183.28"/>
			<lvl_add cp="212.0" hp="424.0" lvl="20" mp="192.0"/>
			<lvl_add cp="229.05" hp="458.1" lvl="21" mp="205.2"/>
			<lvl_add cp="246.255" hp="492.51" lvl="22" mp="218.52"/>
			<lvl_add cp="263.615" hp="527.23" lvl="23" mp="231.96"/>
			<lvl_add cp="281.13" hp="562.26" lvl="24" mp="245.52"/>
			<lvl_add cp="298.8" hp="597.6" lvl="25" mp="259.2"/>
			<lvl_add cp="316.625" hp="633.25" lvl="26" mp="273.0"/>
			<lvl_add cp="334.605" hp="669.21" lvl="27" mp="286.92"/>
			<lvl_add cp="352.74" hp="705.48" lvl="28" mp="300.96"/>
			<lvl_add cp="371.03" hp="742.06" lvl="29" mp="315.12"/>
			<lvl_add cp="389.475" hp="778.95" lvl="30" mp="329.4"/>
			<lvl_add cp="408.075" hp="816.15" lvl="31" mp="343.8"/>
			<lvl_add cp="426.83" hp="853.66" lvl="32" mp="358.32"/>
			<lvl_add cp="445.74" hp="891.48" lvl="33" mp="372.96"/>
			<lvl_add cp="464.805" hp="929.61" lvl="34" mp="387.72"/>
			<lvl_add cp="484.025" hp="968.05" lvl="35" mp="402.6"/>
			<lvl_add cp="503.4" hp="1006.8" lvl="36" mp="417.6"/>
			<lvl_add cp="522.93" hp="1045.86" lvl="37" mp="432.72"/>
			<lvl_add cp="542.615" hp="1085.23" lvl="38" mp="447.96"/>
			<lvl_add cp="562.455" hp="1124.91" lvl="39" mp="463.32"/>
			<lvl_add cp="582.45" hp="1164.9" lvl="40" mp="478.8"/>
			<lvl_add cp="602.6" hp="1205.2" lvl="41" mp="494.4"/>
			<lvl_add cp="622.905" hp="1245.81" lvl="42" mp="510.12"/>
			<lvl_add cp="643.365" hp="1286.73" lvl="43" mp="525.96"/>
			<lvl_add cp="663.98" hp="1327.96" lvl="44" mp="541.92"/>
			<lvl_add cp="684.75" hp="1369.5" lvl="45" mp="558.0"/>
			<lvl_add cp="705.675" hp="1411.35" lvl="46" mp="574.2"/>
			<lvl_add cp="726.755" hp="1453.51" lvl="47" mp="590.52"/>
			<lvl_add cp="747.99" hp="1495.98" lvl="48" mp="606.96"/>
			<lvl_add cp="769.38" hp="1538.76" lvl="49" mp="623.52"/>
			<lvl_add cp="790.925" hp="1581.85" lvl="50" mp="640.2"/>
			<lvl_add cp="812.625" hp="1625.25" lvl="51" mp="657.0"/>
			<lvl_add cp="834.48" hp="1668.96" lvl="52" mp="673.92"/>
			<lvl_add cp="856.49" hp="1712.98" lvl="53" mp="690.96"/>
			<lvl_add cp="878.655" hp="1757.31" lvl="54" mp="708.12"/>
			<lvl_add cp="900.975" hp="1801.95" lvl="55" mp="725.4"/>
			<lvl_add cp="923.45" hp="1846.9" lvl="56" mp="742.8"/>
			<lvl_add cp="946.08" hp="1892.16" lvl="57" mp="760.32"/>
			<lvl_add cp="968.865" hp="1937.73" lvl="58" mp="777.96"/>
			<lvl_add cp="991.805" hp="1983.61" lvl="59" mp="795.72"/>
			<lvl_add cp="1014.9" hp="2029.8" lvl="60" mp="813.6"/>
			<lvl_add cp="1038.15" hp="2076.3" lvl="61" mp="831.6"/>
			<lvl_add cp="1061.555" hp="2123.11" lvl="62" mp="849.72"/>
			<lvl_add cp="1085.115" hp="2170.23" lvl="63" mp="867.96"/>
			<lvl_add cp="1108.83" hp="2217.66" lvl="64" mp="886.32"/>
			<lvl_add cp="1132.7" hp="2265.4" lvl="65" mp="904.8"/>
			<lvl_add cp="1156.725" hp="2313.45" lvl="66" mp="923.4"/>
			<lvl_add cp="1180.905" hp="2361.81" lvl="67" mp="942.12"/>
			<lvl_add cp="1205.24" hp="2410.48" lvl="68" mp="960.96"/>
			<lvl_add cp="1229.73" hp="2459.46" lvl="69" mp="979.92"/>
			<lvl_add cp="1254.375" hp="2508.75" lvl="70" mp="999.0"/>
			<lvl_add cp="1279.175" hp="2558.35" lvl="71" mp="1018.2"/>
			<lvl_add cp="1304.13" hp="2608.26" lvl="72" mp="1037.52"/>
			<lvl_add cp="1329.24" hp="2658.48" lvl="73" mp="1056.96"/>
			<lvl_add cp="1354.505" hp="2709.01" lvl="74" mp="1076.52"/>
			<lvl_add cp="1379.925" hp="2759.85" lvl="75" mp="1096.2"/>
			<lvl_add cp="1405.5" hp="2811.0" lvl="76" mp="1116.0"/>
			<lvl_add cp="1431.23" hp="2862.46" lvl="77" mp="1135.92"/>
			<lvl_add cp="1457.115" hp="2914.23" lvl="78" mp="1155.96"/>
			<lvl_add cp="1483.155" hp="2966.31" lvl="79" mp="1176.12"/>
			<lvl_add cp="1509.35" hp="3018.7" lvl="80" mp="1196.4"/>
			<lvl_add cp="1535.7" hp="3071.4" lvl="81" mp="1216.8"/>
			<lvl_add cp="1562.205" hp="3124.41" lvl="82" mp="1237.32"/>
			<lvl_add cp="1588.865" hp="3177.73" lvl="83" mp="1257.96"/>
			<lvl_add cp="1615.68" hp="3231.36" lvl="84" mp="1278.72"/>
			<lvl_add cp="1642.65" hp="3285.3" lvl="85" mp="1299.6"/>
			<lvl_add cp="1669.775" hp="3339.55" lvl="86" mp="1320.6"/>
			<lvl_add cp="1697.055" hp="3394.11" lvl="87" mp="1341.72"/>
			<lvl_add cp="1724.49" hp="3448.98" lvl="88" mp="1362.96"/>
			<lvl_add cp="1752.08" hp="3504.16" lvl="89" mp="1384.32"/>
			<lvl_add cp="1779.825" hp="3559.65" lvl="90" mp="1405.8"/>
			<lvl_add cp="1807.725" hp="3615.45" lvl="91" mp="1427.4"/>
			<lvl_add cp="1835.78" hp="3671.56" lvl="92" mp="1449.12"/>
			<lvl_add cp="1863.99" hp="3727.98" lvl="93" mp="1470.96"/>
			<lvl_add cp="1892.355" hp="3784.71" lvl="94" mp="1492.92"/>
			<lvl_add cp="1920.875" hp="3841.75" lvl="95" mp="1515.0"/>
			<lvl_add cp="1949.55" hp="3899.1" lvl="96" mp="1537.2"/>
			<lvl_add cp="1978.38" hp="3956.76" lvl="97" mp="1559.52"/>
			<lvl_add cp="2007.365" hp="4014.73" lvl="98" mp="1581.96"/>
			<lvl_add cp="2036.505" hp="4073.01" lvl="99" mp="1604.52"/>
		</lvlupvalues>
	</classtemplate>
</list>

=== BloodyDawn/Ertheia/Data/game/data/stats/player/class_data/[173]Iss Enchanter Spectral Dancer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/CharTemplates.xsd">
	<classtemplate classId="173" classLevel="85" name="Заклинатель Иса" parentClassId="107" raceId="2" serverName="IssEnchanter_SpectralDancer">
		<lvlupvalues>
			<lvl_add cp="47.0" hp="94.0" lvl="1" mp="30.0"/>
			<lvl_add cp="53.825" hp="107.65" lvl="2" mp="35.46"/>
			<lvl_add cp="60.725" hp="121.45" lvl="3" mp="40.98"/>
			<lvl_add cp="67.7" hp="135.4" lvl="4" mp="46.56"/>
			<lvl_add cp="74.75" hp="149.5" lvl="5" mp="52.2"/>
			<lvl_add cp="81.875" hp="163.75" lvl="6" mp="57.9"/>
			<lvl_add cp="89.075" hp="178.15" lvl="7" mp="63.66"/>
			<lvl_add cp="96.35" hp="192.7" lvl="8" mp="69.48"/>
			<lvl_add cp="103.7" hp="207.4" lvl="9" mp="75.36"/>
			<lvl_add cp="111.125" hp="222.25" lvl="10" mp="81.3"/>
			<lvl_add cp="118.625" hp="237.25" lvl="11" mp="87.3"/>
			<lvl_add cp="126.2" hp="252.4" lvl="12" mp="93.36"/>
			<lvl_add cp="133.85" hp="267.7" lvl="13" mp="99.48"/>
			<lvl_add cp="141.575" hp="283.15" lvl="14" mp="105.66"/>
			<lvl_add cp="149.375" hp="298.75" lvl="15" mp="111.9"/>
			<lvl_add cp="157.25" hp="314.5" lvl="16" mp="118.2"/>
			<lvl_add cp="165.2" hp="330.4" lvl="17" mp="124.56"/>
			<lvl_add cp="173.225" hp="346.45" lvl="18" mp="130.98"/>
			<lvl_add cp="181.325" hp="362.65" lvl="19" mp="137.46"/>
			<lvl_add cp="189.5" hp="379.0" lvl="20" mp="144.0"/>
			<lvl_add cp="207.1" hp="414.2" lvl="21" mp="153.9"/>
			<lvl_add cp="224.86" hp="449.72" lvl="22" mp="163.89"/>
			<lvl_add cp="242.78" hp="485.56" lvl="23" mp="173.97"/>
			<lvl_add cp="260.86" hp="521.72" lvl="24" mp="184.14"/>
			<lvl_add cp="279.1" hp="558.2" lvl="25" mp="194.4"/>
			<lvl_add cp="297.5" hp="595.0" lvl="26" mp="204.75"/>
			<lvl_add cp="316.06" hp="632.12" lvl="27" mp="215.19"/>
			<lvl_add cp="334.78" hp="669.56" lvl="28" mp="225.72"/>
			<lvl_add cp="353.66" hp="707.32" lvl="29" mp="236.34"/>
			<lvl_add cp="372.7" hp="745.4" lvl="30" mp="247.05"/>
			<lvl_add cp="391.9" hp="783.8" lvl="31" mp="257.85"/>
			<lvl_add cp="411.26" hp="822.52" lvl="32" mp="268.74"/>
			<lvl_add cp="430.78" hp="861.56" lvl="33" mp="279.72"/>
			<lvl_add cp="450.46" hp="900.92" lvl="34" mp="290.79"/>
			<lvl_add cp="470.3" hp="940.6" lvl="35" mp="301.95"/>
			<lvl_add cp="490.3" hp="980.6" lvl="36" mp="313.2"/>
			<lvl_add cp="510.46" hp="1020.92" lvl="37" mp="324.54"/>
			<lvl_add cp="530.78" hp="1061.56" lvl="38" mp="335.97"/>
			<lvl_add cp="551.26" hp="1102.52" lvl="39" mp="347.49"/>
			<lvl_add cp="571.9" hp="1143.8" lvl="40" mp="359.1"/>
			<lvl_add cp="601.15" hp="1202.3" lvl="41" mp="378.6"/>
			<lvl_add cp="630.625" hp="1261.25" lvl="42" mp="398.25"/>
			<lvl_add cp="660.325" hp="1320.65" lvl="43" mp="418.05"/>
			<lvl_add cp="690.25" hp="1380.5" lvl="44" mp="438.0"/>
			<lvl_add cp="720.4" hp="1440.8" lvl="45" mp="458.1"/>
			<lvl_add cp="750.775" hp="1501.55" lvl="46" mp="478.35"/>
			<lvl_add cp="781.375" hp="1562.75" lvl="47" mp="498.75"/>
			<lvl_add cp="812.2" hp="1624.4" lvl="48" mp="519.3"/>
			<lvl_add cp="843.25" hp="1686.5" lvl="49" mp="540.0"/>
			<lvl_add cp="874.525" hp="1749.05" lvl="50" mp="560.85"/>
			<lvl_add cp="906.025" hp="1812.05" lvl="51" mp="581.85"/>
			<lvl_add cp="937.75" hp="1875.5" lvl="52" mp="603.0"/>
			<lvl_add cp="969.7" hp="1939.4" lvl="53" mp="624.3"/>
			<lvl_add cp="1001.875" hp="2003.75" lvl="54" mp="645.75"/>
			<lvl_add cp="1034.275" hp="2068.55" lvl="55" mp="667.35"/>
			<lvl_add cp="1066.9" hp="2133.8" lvl="56" mp="689.1"/>
			<lvl_add cp="1099.75" hp="2199.5" lvl="57" mp="711.0"/>
			<lvl_add cp="1132.825" hp="2265.65" lvl="58" mp="733.05"/>
			<lvl_add cp="1166.125" hp="2332.25" lvl="59" mp="755.25"/>
			<lvl_add cp="1199.65" hp="2399.3" lvl="60" mp="777.6"/>
			<lvl_add cp="1233.4" hp="2466.8" lvl="61" mp="800.1"/>
			<lvl_add cp="1267.375" hp="2534.75" lvl="62" mp="822.75"/>
			<lvl_add cp="1301.575" hp="2603.15" lvl="63" mp="845.55"/>
			<lvl_add cp="1336.0" hp="2672.0" lvl="64" mp="868.5"/>
			<lvl_add cp="1370.65" hp="2741.3" lvl="65" mp="891.6"/>
			<lvl_add cp="1405.525" hp="2811.05" lvl="66" mp="914.85"/>
			<lvl_add cp="1440.625" hp="2881.25" lvl="67" mp="938.25"/>
			<lvl_add cp="1475.95" hp="2951.9" lvl="68" mp="961.8"/>
			<lvl_add cp="1511.5" hp="3023.0" lvl="69" mp="985.5"/>
			<lvl_add cp="1547.275" hp="3094.55" lvl="70" mp="1009.35"/>
			<lvl_add cp="1583.275" hp="3166.55" lvl="71" mp="1033.35"/>
			<lvl_add cp="1619.5" hp="3239.0" lvl="72" mp="1057.5"/>
			<lvl_add cp="1655.95" hp="3311.9" lvl="73" mp="1081.8"/>
			<lvl_add cp="1692.625" hp="3385.25" lvl="74" mp="1106.25"/>
			<lvl_add cp="1729.525" hp="3459.05" lvl="75" mp="1130.85"/>
			<lvl_add cp="1766.65" hp="3533.3" lvl="76" mp="1155.6"/>
			<lvl_add cp="1804.0" hp="3608.0" lvl="77" mp="1180.5"/>
			<lvl_add cp="1841.575" hp="3683.15" lvl="78" mp="1205.55"/>
			<lvl_add cp="1879.375" hp="3758.75" lvl="79" mp="1230.75"/>
			<lvl_add cp="1917.4" hp="3834.8" lvl="80" mp="1256.1"/>
			<lvl_add cp="1955.65" hp="3911.3" lvl="81" mp="1281.6"/>
			<lvl_add cp="1994.125" hp="3988.25" lvl="82" mp="1307.25"/>
			<lvl_add cp="2032.825" hp="4065.65" lvl="83" mp="1333.05"/>
			<lvl_add cp="2071.75" hp="4143.5" lvl="84" mp="1359.0"/>
			<lvl_add cp="5050.99" hp="4401.8" lvl="85" mp="1846.8"/>
			<lvl_add cp="5100.51" hp="4444.95" lvl="86" mp="1881.8"/>
			<lvl_add cp="5150.52" hp="4488.53" lvl="87" mp="1917.0"/>
			<lvl_add cp="5201.01" hp="4532.53" lvl="88" mp="1952.4"/>
			<lvl_add cp="5252.0" hp="4576.97" lvl="89" mp="1988.0"/>
			<lvl_add cp="5303.49" hp="4621.84" lvl="90" mp="2023.8"/>
			<lvl_add cp="5355.49" hp="4667.16" lvl="91" mp="2059.8"/>
			<lvl_add cp="5407.99" hp="4712.91" lvl="92" mp="2096.0"/>
			<lvl_add cp="5461.01" hp="4759.12" lvl="93" mp="2132.4"/>
			<lvl_add cp="5514.55" hp="4805.77" lvl="94" mp="2169.0"/>
			<lvl_add cp="5568.61" hp="4852.89" lvl="95" mp="2205.8"/>
			<lvl_add cp="5623.21" hp="4900.47" lvl="96" mp="2242.8"/>
			<lvl_add cp="5678.34" hp="4948.51" lvl="97" mp="2280.0"/>
			<lvl_add cp="5734.01" hp="4997.03" lvl="98" mp="2317.4"/>
			<lvl_add cp="5790.22" hp="5046.02" lvl="99" mp="2355.0"/>
		</lvlupvalues>
	</classtemplate>
</list>

=== BloodyDawn/Ertheia/Data/game/data/stats/player/class_data/[038]DE Mage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/CharTemplates.xsd">
	<classtemplate classId="38" classLevel="1" name="Тёмный Мистик" raceId="2" serverName="dark_mage">
		<lvlupvalues>
			<lvl_add cp="53.0" hp="106.0" lvl="1" mp="40.0"/>
			<lvl_add cp="60.735" hp="121.47" lvl="2" mp="47.28"/>
			<lvl_add cp="68.555" hp="137.11" lvl="3" mp="54.64"/>
			<lvl_add cp="76.46" hp="152.92" lvl="4" mp="62.08"/>
			<lvl_add cp="84.45" hp="168.9" lvl="5" mp="69.6"/>
			<lvl_add cp="92.525" hp="185.05" lvl="6" mp="77.2"/>
			<lvl_add cp="100.685" hp="201.37" lvl="7" mp="84.88"/>
			<lvl_add cp="108.93" hp="217.86" lvl="8" mp="92.64"/>
			<lvl_add cp="117.26" hp="234.52" lvl="9" mp="100.48"/>
			<lvl_add cp="125.675" hp="251.35" lvl="10" mp="108.4"/>
			<lvl_add cp="134.175" hp="268.35" lvl="11" mp="116.4"/>
			<lvl_add cp="142.76" hp="285.52" lvl="12" mp="124.48"/>
			<lvl_add cp="151.43" hp="302.86" lvl="13" mp="132.64"/>
			<lvl_add cp="160.185" hp="320.37" lvl="14" mp="140.88"/>
			<lvl_add cp="169.025" hp="338.05" lvl="15" mp="149.2"/>
			<lvl_add cp="177.95" hp="355.9" lvl="16" mp="157.6"/>
			<lvl_add cp="186.96" hp="373.92" lvl="17" mp="166.08"/>
			<lvl_add cp="196.055" hp="392.11" lvl="18" mp="174.64"/>
			<lvl_add cp="205.235" hp="410.47" lvl="19" mp="183.28"/>
			<lvl_add cp="214.5" hp="429.0" lvl="20" mp="192.0"/>
			<lvl_add cp="223.85" hp="447.7" lvl="21" mp="200.8"/>
			<lvl_add cp="233.285" hp="466.57" lvl="22" mp="209.68"/>
			<lvl_add cp="242.805" hp="485.61" lvl="23" mp="218.64"/>
			<lvl_add cp="252.41" hp="504.82" lvl="24" mp="227.68"/>
			<lvl_add cp="262.1" hp="524.2" lvl="25" mp="236.8"/>
			<lvl_add cp="271.875" hp="543.75" lvl="26" mp="246.0"/>
			<lvl_add cp="281.735" hp="563.47" lvl="27" mp="255.28"/>
			<lvl_add cp="291.68" hp="583.36" lvl="28" mp="264.64"/>
			<lvl_add cp="301.71" hp="603.42" lvl="29" mp="274.08"/>
			<lvl_add cp="311.825" hp="623.65" lvl="30" mp="283.6"/>
			<lvl_add cp="322.025" hp="644.05" lvl="31" mp="293.2"/>
			<lvl_add cp="332.31" hp="664.62" lvl="32" mp="302.88"/>
			<lvl_add cp="342.68" hp="685.36" lvl="33" mp="312.64"/>
			<lvl_add cp="353.135" hp="706.27" lvl="34" mp="322.48"/>
			<lvl_add cp="363.675" hp="727.35" lvl="35" mp="332.4"/>
			<lvl_add cp="374.3" hp="748.6" lvl="36" mp="342.4"/>
			<lvl_add cp="385.01" hp="770.02" lvl="37" mp="352.48"/>
			<lvl_add cp="395.805" hp="791.61" lvl="38" mp="362.64"/>
			<lvl_add cp="406.685" hp="813.37" lvl="39" mp="372.88"/>
			<lvl_add cp="417.65" hp="835.3" lvl="40" mp="383.2"/>
			<lvl_add cp="428.7" hp="857.4" lvl="41" mp="393.6"/>
			<lvl_add cp="439.835" hp="879.67" lvl="42" mp="404.08"/>
			<lvl_add cp="451.055" hp="902.11" lvl="43" mp="414.64"/>
			<lvl_add cp="462.36" hp="924.72" lvl="44" mp="425.28"/>
			<lvl_add cp="473.75" hp="947.5" lvl="45" mp="436.0"/>
			<lvl_add cp="485.225" hp="970.45" lvl="46" mp="446.8"/>
			<lvl_add cp="496.785" hp="993.57" lvl="47" mp="457.68"/>
			<lvl_add cp="508.43" hp="1016.86" lvl="48" mp="468.64"/>
			<lvl_add cp="520.16" hp="1040.32" lvl="49" mp="479.68"/>
			<lvl_add cp="531.975" hp="1063.95" lvl="50" mp="490.8"/>
			<lvl_add cp="543.875" hp="1087.75" lvl="51" mp="502.0"/>
			<lvl_add cp="555.86" hp="1111.72" lvl="52" mp="513.28"/>
			<lvl_add cp="567.93" hp="1135.86" lvl="53" mp="524.64"/>
			<lvl_add cp="580.085" hp="1160.17" lvl="54" mp="536.08"/>
			<lvl_add cp="592.325" hp="1184.65" lvl="55" mp="547.6"/>
			<lvl_add cp="604.65" hp="1209.3" lvl="56" mp="559.2"/>
			<lvl_add cp="617.06" hp="1234.12" lvl="57" mp="570.88"/>
			<lvl_add cp="629.555" hp="1259.11" lvl="58" mp="582.64"/>
			<lvl_add cp="642.135" hp="1284.27" lvl="59" mp="594.48"/>
			<lvl_add cp="654.8" hp="1309.6" lvl="60" mp="606.4"/>
			<lvl_add cp="667.55" hp="1335.1" lvl="61" mp="618.4"/>
			<lvl_add cp="680.385" hp="1360.77" lvl="62" mp="630.48"/>
			<lvl_add cp="693.305" hp="1386.61" lvl="63" mp="642.64"/>
			<lvl_add cp="706.31" hp="1412.62" lvl="64" mp="654.88"/>
			<lvl_add cp="719.4" hp="1438.8" lvl="65" mp="667.2"/>
			<lvl_add cp="732.575" hp="1465.15" lvl="66" mp="679.6"/>
			<lvl_add cp="745.835" hp="1491.67" lvl="67" mp="692.08"/>
			<lvl_add cp="759.18" hp="1518.36" lvl="68" mp="704.64"/>
			<lvl_add cp="772.61" hp="1545.22" lvl="69" mp="717.28"/>
			<lvl_add cp="786.125" hp="1572.25" lvl="70" mp="730.0"/>
			<lvl_add cp="799.725" hp="1599.45" lvl="71" mp="742.8"/>
			<lvl_add cp="813.41" hp="1626.82" lvl="72" mp="755.68"/>
			<lvl_add cp="827.18" hp="1654.36" lvl="73" mp="768.64"/>
			<lvl_add cp="841.035" hp="1682.07" lvl="74" mp="781.68"/>
			<lvl_add cp="854.975" hp="1709.95" lvl="75" mp="794.8"/>
			<lvl_add cp="869.0" hp="1738.0" lvl="76" mp="808.0"/>
			<lvl_add cp="883.11" hp="1766.22" lvl="77" mp="821.28"/>
			<lvl_add cp="897.305" hp="1794.61" lvl="78" mp="834.64"/>
			<lvl_add cp="911.585" hp="1823.17" lvl="79" mp="848.08"/>
			<lvl_add cp="925.95" hp="1851.9" lvl="80" mp="861.6"/>
			<lvl_add cp="940.4" hp="1880.8" lvl="81" mp="875.2"/>
			<lvl_add cp="954.935" hp="1909.87" lvl="82" mp="888.88"/>
			<lvl_add cp="969.555" hp="1939.11" lvl="83" mp="902.64"/>
			<lvl_add cp="984.26" hp="1968.52" lvl="84" mp="916.48"/>
			<lvl_add cp="999.05" hp="1998.1" lvl="85" mp="930.4"/>
			<lvl_add cp="1013.925" hp="2027.85" lvl="86" mp="944.4"/>
			<lvl_add cp="1028.885" hp="2057.77" lvl="87" mp="958.48"/>
			<lvl_add cp="1043.93" hp="2087.86" lvl="88" mp="972.64"/>
			<lvl_add cp="1059.06" hp="2118.12" lvl="89" mp="986.88"/>
			<lvl_add cp="1074.275" hp="2148.55" lvl="90" mp="1001.2"/>
			<lvl_add cp="1089.575" hp="2179.15" lvl="91" mp="1015.6"/>
			<lvl_add cp="1104.96" hp="2209.92" lvl="92" mp="1030.08"/>
			<lvl_add cp="1120.43" hp="2240.86" lvl="93" mp="1044.64"/>
			<lvl_add cp="1135.985" hp="2271.97" lvl="94" mp="1059.28"/>
			<lvl_add cp="1151.625" hp="2303.25" lvl="95" mp="1074.0"/>
			<lvl_add cp="1167.35" hp="2334.7" lvl="96" mp="1088.8"/>
			<lvl_add cp="1183.16" hp="2366.32" lvl="97" mp="1103.68"/>
			<lvl_add cp="1199.055" hp="2398.11" lvl="98" mp="1118.64"/>
			<lvl_add cp="1215.035" hp="2430.07" lvl="99" mp="1133.68"/>
		</lvlupvalues>
	</classtemplate>
</list>
