=== BloodyDawn/Ertheia/Data/game/data/xsd/locationSpawnlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list" type="listType" />
	<xs:complexType name="spawnsType">
		<xs:sequence>
			<xs:element type="npcType" name="npc" maxOccurs="unbounded" minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" />
		<xs:attribute type="xs:string" name="isCustom" />
		<xs:attribute type="xs:string" name="isCustom2" />
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence>
			<xs:element type="spawnsType" name="spawns" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="npcType">
		<xs:sequence>
			<xs:element type="spawnType" name="spawn" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:integer" name="id" use="optional" />
	</xs:complexType>
	<xs:complexType name="spawnType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:integer" name="x" use="optional" />
				<xs:attribute type="xs:integer" name="y" use="optional" />
				<xs:attribute type="xs:integer" name="z" use="optional" />
				<xs:attribute type="xs:integer" name="heading" use="optional" />
				<xs:attribute type="xs:integer" name="respawn" use="optional" />
				<xs:attribute type="xs:integer" name="periodOfDay" use="optional" />
				<xs:attribute type="xs:integer" name="count" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== BloodyDawn/Ertheia/Data/game/data/stats/npc/spawn/static/16_19.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/locationSpawnlist.xsd">
	<spawns name="16_19">
		
		<npc id="32133">
			<spawn heading="0" x="-125872" y="38208" z="1232"/>
		</npc>
		
		<npc id="32134">
			<spawn heading="0" x="-125872" y="38016" z="1232"/>
		</npc>
		
		<npc id="32136">
			<spawn heading="0" x="-122400" y="38432" z="1440"/>
		</npc>
		
		<npc id="32137">
			<spawn heading="0" x="-122396" y="37784" z="1432"/>
		</npc>
		
		<npc id="32179">
			<spawn heading="63440" x="-110544" y="49040" z="-1128"/>
		</npc>
		
		<npc id="32180">
			<spawn heading="3072" x="-110536" y="45162" z="-1128"/>
		</npc>
		
		<npc id="32191">
			<spawn heading="8172" x="-124624" y="51584" z="-552"/>
		</npc>
		
		<npc id="32192">
			<spawn heading="22896" x="-124064" y="51584" z="-552"/>
		</npc>
	</spawns>
</list>

=== BloodyDawn/Ertheia/Data/game/data/stats/npc/spawn/static/towns/Gludio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../xsd/locationSpawnlist.xsd">
	<spawns name="Gludio">
		
		<npc id="30030">
			<spawn heading="49152" respawn="0" x="-13269" y="121884" z="-2968"/>
		</npc>
		
		<npc id="30144">
			<spawn heading="29411" respawn="0" x="-12526" y="123232" z="-3096"/>
		</npc>
		
		<npc id="30155">
			<spawn heading="28170" respawn="0" x="-13553" y="122617" z="-3104"/>
		</npc>
		
		<npc id="30158">
			<spawn heading="36484" respawn="0" x="-12926" y="121825" z="-2968"/>
		</npc>
		
		<npc id="30253">
			<spawn heading="12288" respawn="0" x="-15132" y="123282" z="-3107"/>
		</npc>
		
		<npc id="30254">
			<spawn heading="61440" respawn="0" x="-14934" y="124468" z="-3114"/>
		</npc>
		
		<npc id="30255">
			<spawn heading="49152" respawn="0" x="-13132" y="124988" z="-3112"/>
		</npc>
		
		<npc id="30256">
			<spawn heading="0" respawn="0" x="-14531" y="124060" z="-3120"/>
		</npc>
		
		<npc id="30288">
			<spawn heading="35672" respawn="0" x="-13579" y="123017" z="-3104"/>
		</npc>
		
		<npc id="30289">
			<spawn heading="32765" respawn="0" x="-12784" y="121709" z="-2952"/>
		</npc>
		
		<npc id="30293">
			<spawn heading="16384" respawn="0" x="-13487" y="121541" z="-2968"/>
		</npc>
		
		<npc id="30294">
			<spawn heading="4096" respawn="0" x="-14933" y="124540" z="-3115"/>
		</npc>
		
		<npc id="30297">
			<spawn heading="4835" respawn="0" x="-12892" y="123143" z="-3096"/>
		</npc>
		
		<npc id="30298">
			<spawn heading="57344" respawn="0" x="-15349" y="124763" z="-3112"/>
		</npc>
		
		<npc id="30321">
			<spawn heading="20480" respawn="0" x="-15238" y="123282" z="-3107"/>
		</npc>
		
		<npc id="30322">
			<spawn heading="16384" respawn="0" x="-13049" y="124737" z="-3112"/>
		</npc>
		
		<npc id="30325">
			<spawn heading="40960" respawn="0" x="-13419" y="123068" z="-3104"/>
		</npc>
		
		<npc id="30326">
			<spawn heading="57344" respawn="0" x="-13691" y="123068" z="-3104"/>
		</npc>
		
		<npc id="30327">
			<spawn heading="28672" respawn="0" x="-13440" y="122643" z="-3104"/>
		</npc>
		
		<npc id="30328">
			<spawn heading="8192" respawn="0" x="-13693" y="122583" z="-3104"/>
		</npc>
		
		<npc id="30329">
			<spawn heading="49152" respawn="0" x="-12791" y="123259" z="-3096"/>
		</npc>
		
		<npc id="30330">
			<spawn heading="32768" respawn="0" x="-12503" y="123054" z="-3096"/>
		</npc>
		
		<npc id="30331">
			<spawn heading="49152" respawn="0" x="-14708" y="121020" z="-2984"/>
		</npc>
		
		<npc id="30332">
			<spawn heading="49552" respawn="0" x="-13900" y="123822" z="-3112"/>
		</npc>
		
		<npc id="30333">
			<spawn heading="33190" respawn="0" x="-16623" y="124028" z="-3112"/>
		</npc>
		
		<npc id="30334">
			<spawn heading="54175" respawn="0" x="-16621" y="124330" z="-3112"/>
		</npc>
		
		<npc id="30335">
			<spawn heading="16384" respawn="0" x="-14336" y="126546" z="-3144"/>
		</npc>
		
		<npc id="30336">
			<spawn heading="16384" respawn="0" x="-14005" y="126542" z="-3144"/>
		</npc>
		
		<npc id="30337">
			<spawn heading="0" respawn="0" x="-11940" y="123789" z="-3080"/>
		</npc>
		
		<npc id="30338">
			<spawn heading="0" respawn="0" x="-11950" y="123473" z="-3088"/>
		</npc>
		
		<npc id="30342">
			<spawn heading="32768" respawn="0" x="-12188" y="122899" z="-3096"/>
		</npc>
		
		<npc id="30344">
			<spawn heading="16384" respawn="0" x="-13269" y="121540" z="-2968"/>
		</npc>
		
		<npc id="30345">
			<spawn heading="49152" respawn="0" x="-13487" y="121884" z="-2968"/>
		</npc>
		
		<npc id="30416">
			<spawn heading="16384" respawn="0" x="-12506" y="123405" z="-3112"/>
		</npc>
		
		<npc id="30434">
			<spawn heading="32768" respawn="0" x="-14977" y="126035" z="-3144"/>
		</npc>
		
		<npc id="30503">
			<spawn heading="0" respawn="0" x="-13323" y="124989" z="-3112"/>
		</npc>
		
		<npc id="30504">
			<spawn heading="43821" respawn="0" x="-15190" y="124756" z="-3112"/>
		</npc>
		
		<npc id="30505">
			<spawn heading="57310" respawn="0" x="-12823" y="124887" z="-3126"/>
		</npc>
		
		<npc id="30506">
			<spawn heading="0" respawn="0" x="-12788" y="124764" z="-3120"/>
		</npc>
		
		<npc id="30507">
			<spawn heading="0" respawn="0" x="-12788" y="124976" z="-3117"/>
		</npc>
		
		<npc id="30729">
			<spawn heading="16384" respawn="0" x="-15443" y="124913" z="-3112"/>
		</npc>
		
		<npc id="30767">
			<spawn heading="0" respawn="0" x="-14767" y="122955" z="-3112"/>
		</npc>
		
		<npc id="30827">
			<spawn heading="16384" respawn="0" x="-13908" y="123322" z="-3112"/>
		</npc>
		
		<npc id="31047">
			<spawn heading="15972" respawn="0" x="-14708" y="124160" z="-3112"/>
		</npc>
		
		<npc id="31077">
			<spawn heading="0" respawn="0" x="-14739" y="124036" z="-3120"/>
		</npc>
		
		<npc id="31092">
			<spawn heading="0" respawn="0" x="-12345" y="121695" z="-2984"/>
		</npc>
		
		<npc id="31440">
			<spawn heading="0" respawn="0" x="-15440" y="124592" z="-3112"/>
		</npc>
		
		<npc id="31568">
			<spawn heading="49000" respawn="0" x="-14768" y="124704" z="-3112"/>
		</npc>
		
		<npc id="31688">
			<spawn heading="3000" respawn="0" x="-15120" y="122096" z="-3064"/>
		</npc>
		
		<npc id="31690">
			<spawn heading="3000" respawn="0" x="-15104" y="122040" z="-3056"/>
		</npc>
		
		<npc id="31792">
			<spawn heading="0" respawn="0" x="-13328" y="122720" z="-3048"/>
		</npc>
		
		<npc id="31793">
			<spawn heading="16500" respawn="0" x="-12466" y="123408" z="-3112"/>
		</npc>
		
		<npc id="31794">
			<spawn heading="49000" respawn="0" x="-13944" y="126384" z="-3144"/>
		</npc>
		
		<npc id="31795">
			<spawn heading="49000" respawn="0" x="-15518" y="124297" z="-3112"/>
		</npc>
		
		<npc id="31796">
			<spawn heading="0" respawn="0" x="-16464" y="123952" z="-3120"/>
		</npc>
		
		<npc id="32196">
			<spawn heading="48486" respawn="0" x="-13527" y="125585" z="-3128"/>
		</npc>
		
		<npc id="32197">
			<spawn heading="49151" respawn="0" x="-13489" y="125562" z="-3128"/>
		</npc>
		
		<npc id="32198">
			<spawn heading="49151" respawn="0" x="-13565" y="125562" z="-3128"/>
		</npc>
		
		<npc id="32478">
			<spawn heading="49000" respawn="0" x="-13232" y="124624" z="-3104"/>
		</npc>
		
		<npc id="32479">
			<spawn heading="49152" respawn="0" x="-14409" y="121023" z="-2984"/>
		</npc>
		
		<npc id="32484">
			<spawn heading="49588" respawn="0" x="-13948" y="123819" z="-3112"/>
		</npc>
		
		<npc id="32575">
			<spawn heading="15991" respawn="0" x="-12967" y="122166" z="-2984"/>
		</npc>
		
		<npc id="32576">
			<spawn heading="32768" respawn="0" x="-13976" y="121399" z="-2984"/>
		</npc>
		
		<npc id="32875">
			<spawn heading="25662" respawn="0" x="-15162" y="124616" z="-3112"/>
		</npc>
		
		<npc id="33359">
			<spawn heading="65363" respawn="0" x="-14764" y="122994" z="-3112"/>
		</npc>
		
		<npc id="33463">
			<spawn heading="50760" respawn="0" x="-14675" y="124025" z="-3120"/>
		</npc>
		
		<npc id="33494">
			<spawn heading="23847" respawn="0" x="-14691" y="124173" z="-3112"/>
		</npc>
		
		<npc id="33552">
			<spawn heading="65502" respawn="0" x="-14760" y="122892" z="-3112"/>
		</npc>
		
		<npc id="33587">
			<spawn heading="64382" respawn="0" x="-14742" y="122829" z="-3112"/>
		</npc>
		
		<npc id="33685">
			<spawn heading="64246" respawn="0" x="-15128" y="122147" z="-3072"/>
		</npc>
		
		<npc id="33759">
			<spawn heading="4835" respawn="0" x="-14741" y="122770" z="-3112"/>
		</npc>
		
		<npc id="33792">
			<spawn heading="33220" respawn="0" x="-14126" y="124066" z="-3112"/>
		</npc>
		
		<npc id="35103">
			<spawn heading="32672" respawn="0" x="-15160" y="124292" z="-3112"/>
			<spawn heading="14446" respawn="0" x="-14060" y="121350" z="-2984"/>
		</npc>
		
		<npc id="35384">
			<spawn heading="53248" respawn="0" x="-16159" y="123728" z="-3096"/>
		</npc>
		
		<npc id="35385">
			<spawn heading="13288" respawn="0" x="-15882" y="123788" z="-3112"/>
		</npc>
		
		<npc id="35386">
			<spawn heading="16384" respawn="0" x="-14852" y="125413" z="-3128"/>
		</npc>
		
		<npc id="35387">
			<spawn heading="0" respawn="0" x="-14731" y="125630" z="-3136"/>
		</npc>
		
		<npc id="35388">
			<spawn heading="32768" respawn="0" x="-13745" y="125573" z="-3128"/>
		</npc>
		
		<npc id="35389">
			<spawn heading="32768" respawn="0" x="-14145" y="125551" z="-3136"/>
		</npc>
		
		<npc id="35390">
			<spawn heading="57344" respawn="0" x="-12866" y="124166" z="-3096"/>
		</npc>
		
		<npc id="35391">
			<spawn heading="49152" respawn="0" x="-12693" y="123815" z="-3112"/>
		</npc>
        <npc id="30990">
            <spawn heading="48000" respawn="0" x="-12676" y="122821" z="-3112"/>
        </npc>
	</spawns>
</list>
