=== BloodyDawn/Ertheia/Data/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list" type="listType"/>
	<xs:complexType name="ingredientType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="count" use="optional"/>
				<xs:attribute type="xs:string" name="id" use="optional"/>
				<xs:attribute type="xs:string" name="enchant" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="configType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="showall"/>
				<xs:attribute type="xs:string" name="notax"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence>
		<xs:element type="configType" name="config" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="itemType" name="item" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="taxFree"/>
		<xs:attribute type="xs:string" name="showAll"/>
		<xs:attribute type="xs:string" name="keepEnchant"/>
		<xs:attribute type="xs:string" name="allowAugmentedItems"/>
		<xs:attribute type="xs:string" name="allowElementalItems"/>
		<xs:attribute type="xs:string" name="chanceBuy"/>
		<xs:attribute type="xs:string" name="npcCheck"/>
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element type="ingredientType" name="ingredient" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="productionType" name="production" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="optional"/>
	</xs:complexType>
	<xs:complexType name="productionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="count" use="optional"/>
				<xs:attribute type="xs:string" name="id" use="optional"/>
		<xs:attribute type="xs:string" name="chance" use="optional"/>
		<xs:attribute type="xs:string" name="enchant" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== BloodyDawn/Ertheia/Data/game/data/stats/shop/multisell/normal/617.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance" allowAugmentedItems="true" allowElementalItems="true" keepEnchant="true" ns0:noNamespaceSchemaLocation="../../../../xsd/multisell.xsd" showAll="true" taxFree="true">
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9417"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9418"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9419"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9420"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10228"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10229"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10230"/>
	</item>
	<item>
		
		<ingredient count="1" id="9416"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10231"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9426"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9427"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="10126"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="10127"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="10168"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="10214"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10233"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10234"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10487"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10488"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10489"/>
	</item>
	<item>
		
		<ingredient count="1" id="9425"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10490"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9433"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9434"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9435"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="9451"/>
		
		<production count="1" id="9436"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10236"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10237"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10238"/>
	</item>
	<item>
		
		<ingredient count="1" id="9432"/>
		
		<ingredient count="1" id="10413"/>
		
		<production count="1" id="10239"/>
	</item>
</list>

=== BloodyDawn/Ertheia/Data/game/data/stats/shop/multisell/custom/default/11007.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance" taxFree="true" showAll="true" keepEnchant="false" allowAugmentedItems="false"
	  allowElementalItems="false" npcCheck="false"
	  ns0:noNamespaceSchemaLocation="../../../../../xsd/multisell.xsd">
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Острие Реквиема -->
		<production id="17290" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Резак Реквиема -->
		<production id="17291" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Эспадон Реквиема -->
		<production id="17292" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Мститель Реквиема -->
		<production id="17293" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Воитель Реквиема -->
		<production id="17294" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Буревестник Реквиема -->
		<production id="17295" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Бросок Реквиема -->
		<production id="17296" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Страж Реквиема -->
		<production id="17297" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Расчленитель Реквиема -->
		<production id="17298" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Заклинатель Реквиема -->
		<production id="17299" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Возмездие Реквиема -->
		<production id="17300" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Парные Мечи Реквиема -->
		<production id="17301" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Парные Кинжалы Реквиема -->
		<production id="17302" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="120000000"/>
		<!-- Парные Дубины Реквиема -->
		<production id="17303" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Острие Апокалипсиса -->
		<production id="17324" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Резак Апокалипсиса -->
		<production id="17325" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Эспадон Апокалипсиса -->
		<production id="17326" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Мститель Апокалипсиса -->
		<production id="17327" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Воитель Апокалипсиса -->
		<production id="17328" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Буревестник Апокалипсиса -->
		<production id="17329" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Бросок Апокалипсиса -->
		<production id="17330" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Страж Апокалипсиса -->
		<production id="17331" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Расчленитель Апокалипсиса -->
		<production id="17332" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Заклинатель Апокалипсиса -->
		<production id="17333" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Возмездие Апокалипсиса -->
		<production id="17334" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Парные Мечи Апокалипсиса -->
		<production id="17335" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Парные Кинжалы Апокалипсиса -->
		<production id="17336" count="1"/>
	</item>
	<item>
		<!-- Адена -->
		<ingredient id="57" count="150000000"/>
		<!-- Парные Дубины Апокалипсиса -->
		<production id="17337" count="1"/>
	</item>
</list>

=== BloodyDawn/Ertheia/Data/game/custom/multisell/community_board/2000001.xml
<?xml version="1.0" encoding="utf-8"?>
<list taxFree="true" showAll="true" keepEnchant="false" allowAugmentedItems="false" allowElementalItems="false"
	  npcCheck="false" xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance"
	  ns0:noNamespaceSchemaLocation="./../../../data/xsd/multisell.xsd">
	 <!-- Blue Wolf Heavy Armor -->
  <item id="1">
    <ingredient id="57" count="6000000"/>
    <production id="358" count="1"/>
    <production id="2380" count="1"/>
    <production id="5718" count="1"/>
    <production id="5734" count="1"/>
    <production id="2416" count="1"/>
    <production id="673" count="1"/>
  </item>

  <!-- Blue Wolf Leather Armor -->
  <item id="2">
    <ingredient id="57" count="6000000"/>
    <production id="2391" count="1"/>
    <production id="2416" count="1"/>
    <production id="5719" count="1"/>
    <production id="5735" count="1"/>
  </item>

  <!-- Blue Wolf Robe Armor -->
  <item id="3">
    <ingredient id="57" count="6000000"/>
    <production id="2398" count="1"/>
    <production id="2403" count="1"/>
    <production id="2416" count="1"/>
    <production id="5736" count="1"/>
    <production id="5720" count="1"/>
  </item>

  <!-- Avadon Heavy Armor -->
  <item id="4">
    <ingredient id="57" count="6000000"/>
    <production id="2376" count="1"/>
    <production id="2379" count="1"/>
    <production id="2415" count="1"/>
    <production id="5714" count="1"/>
    <production id="5730" count="1"/>
    <production id="673" count="1"/>
  </item>

  <!-- Avadon Leather Armor -->
  <item id="5">
    <ingredient id="57" count="6000000"/>
    <production id="2390" count="1"/>
    <production id="2415" count="1"/>
    <production id="5715" count="1"/>
    <production id="5731" count="1"/>
  </item>

  <!-- Avadon Robe Armor -->
  <item id="6">
    <ingredient id="57" count="6000000"/>
    <production id="2406" count="1"/>
    <production id="673" count="1"/>
    <production id="2415" count="1"/>
    <production id="5716" count="1"/>
    <production id="5732" count="1"/>
  </item>

  <!-- Doom Heavy Armor -->
  <item id="7">
    <ingredient id="57" count="6000000"/>
    <production id="2381" count="1"/>
    <production id="2417" count="1"/>
    <production id="5722" count="1"/>
    <production id="5738" count="1"/>
    <production id="110" count="1"/>
  </item>

  <!-- Doom Leather Armor -->
  <item id="8">
    <ingredient id="57" count="6000000"/>
    <production id="2392" count="1"/>
    <production id="2417" count="1"/>
    <production id="5723" count="1"/>
    <production id="5739" count="1"/>
  </item>

  <!-- Doom Robe Armor -->
  <item id="9">
    <ingredient id="57" count="6000000"/>
    <production id="2399" count="1"/>
    <production id="2404" count="1"/>
    <production id="2417" count="1"/>
    <production id="5724" count="1"/>
    <production id="5740" count="1"/>
  </item>

  <!-- Zubei's Heavy Armor -->
  <item id="10">
    <ingredient id="57" count="6000000"/>
    <production id="357" count="1"/>
    <production id="383" count="1"/>
    <production id="503" count="1"/>
    <production id="5710" count="1"/>
    <production id="5726" count="1"/>
    <production id="633" count="1"/>
  </item>

  <!-- Zubei's Leather Armor -->
  <item id="11">
    <ingredient id="57" count="6000000"/>
    <production id="2384" count="1"/>
    <production id="2388" count="1"/>
    <production id="503" count="1"/>
    <production id="5711" count="1"/>
    <production id="5727" count="1"/>
  </item>

  <!-- Zubei's Robe Armor -->
  <item id="12">
    <ingredient id="57" count="6000000"/>
    <production id="2397" count="1"/>
    <production id="503" count="1"/>
    <production id="2402" count="1"/>
    <production id="5712" count="1"/>
    <production id="5728" count="1"/>
  </item>
  
  
  <!-- Majestic Heavy Armor -->
  <item id="1">
    <ingredient id="57" count="15000000"/>
    <production id="2383" count="1"/>
    <production id="2419" count="1"/>
    <production id="5774" count="1"/>
    <production id="5786" count="1"/>
  </item>

  <!-- Majestic Leather Armor -->
  <item id="2">
    <ingredient id="57" count="15000000"/>
    <production id="2395" count="1"/>
    <production id="2419" count="1"/>
    <production id="5775" count="1"/>
    <production id="5787" count="1"/>
  </item>

  <!-- Majestic Robe Armor -->
  <item id="3">
    <ingredient id="57" count="15000000"/>
    <production id="2409" count="1"/>
    <production id="2419" count="1"/>
    <production id="5776" count="1"/>
    <production id="5788" count="1"/>
  </item>

  <!-- Tallum Heavy Armor -->
  <item id="4">
    <ingredient id="57" count="15000000"/>
    <production id="2382" count="1"/>
    <production id="547" count="1"/>
    <production id="5768" count="1"/>
    <production id="5780" count="1"/>
  </item>

  <!-- Tallum Leather Armor -->
  <item id="5">
    <ingredient id="57" count="15000000"/>
    <production id="2393" count="1"/>
    <production id="547" count="1"/>
    <production id="5769" count="1"/>
    <production id="5781" count="1"/>
  </item>

  <!-- Tallum Robe Armor -->
  <item id="6">
    <ingredient id="57" count="15000000"/>
    <production id="2400" count="1"/>
    <production id="2405" count="1"/>
    <production id="547" count="1"/>
    <production id="5770" count="1"/>
    <production id="5782" count="1"/>
  </item>

  <!-- Dark Crystal Heavy Armor -->
  <item id="7">
    <ingredient id="57" count="15000000"/>
    <production id="365" count="1"/>
    <production id="388" count="1"/>
    <production id="512" count="1"/>
    <production id="5765" count="1"/>
    <production id="5777" count="1"/>
    <production id="641" count="1"/>
  </item>

  <!-- Dark Crystal Light Armor -->
  <item id="8">
    <ingredient id="57" count="15000000"/>
    <production id="2385" count="1"/>
    <production id="2389" count="1"/>
    <production id="512" count="1"/>
    <production id="5766" count="1"/>
    <production id="5778" count="1"/>
  </item>

  <!-- Dark Crystal Robe Armor -->
  <item id="9">
    <ingredient id="57" count="15000000"/>
    <production id="2407" count="1"/>
    <production id="512" count="1"/>
    <production id="5767" count="1"/>
    <production id="5779" count="1"/>
  </item>

  <!-- Nightmare Heavy Armor -->
  <item id="10">
    <ingredient id="57" count="15000000"/>
    <production id="374" count="1"/>
    <production id="2418" count="1"/>
    <production id="5771" count="1"/>
    <production id="5783" count="1"/>
    <production id="2498" count="1"/>
  </item>

  <!-- Nightmare Leather Armor -->
  <item id="11">
    <ingredient id="57" count="15000000"/>
    <production id="2394" count="1"/>
    <production id="2418" count="1"/>
    <production id="5772" count="1"/>
    <production id="5784" count="1"/>
  </item>

  <!-- Nightmare Robe Armor -->
  <item id="12">
    <ingredient id="57" count="15000000"/>
    <production id="2408" count="1"/>
    <production id="2418" count="1"/>
    <production id="5773" count="1"/>
    <production id="5785" count="1"/>
  </item>

    <!-- Apella Heavy -->
  <item id="13">
    <ingredient id="57" count="15000000"/>
    <production id="7861" count="1"/>
    <production id="7860" count="1"/>
    <production id="7862" count="1"/>
    <production id="7863" count="1"/>
  </item>
  
    <!-- Apella Light -->
  <item id="14">
    <ingredient id="57" count="15000000"/>
    <production id="7864" count="1"/>
    <production id="7860" count="1"/>
    <production id="7865" count="1"/>
    <production id="7866" count="1"/>
  </item>
  
    <!-- Apella Robe -->
  <item id="15">
    <ingredient id="57" count="15000000"/>
    <production id="7867" count="1"/>
    <production id="7860" count="1"/>
    <production id="7868" count="1"/>
    <production id="7869" count="1"/>
  </item>
  
   <!-- Draconic Leather Armor -->
  <item id="1">
    <ingredient id="57" count="25000000"/>
    <production id="6379" count="1"/>
    <production id="6381" count="1"/>
    <production id="6380" count="1"/>
    <production id="6382" count="1"/>
  </item>

  <!-- Imperial Crusader Heavy Armor -->
  <item id="2">
    <ingredient id="57" count="30000000"/>
    <production id="6373" count="1"/>
    <production id="6374" count="1"/>
    <production id="6375" count="1"/>
    <production id="6376" count="1"/>
    <production id="6377" count="1"/>
    <production id="6378" count="1"/>
  </item>

  <!-- Major Arcana Robe Armor -->
  <item id="3">
    <ingredient id="57" count="30000000"/>
    <production id="6383" count="1"/>
    <production id="6384" count="1"/>
    <production id="6385" count="1"/>
    <production id="6386" count="1"/>
	<production id="12811" count="1"/>
  </item>
</list>

=== BloodyDawn/Ertheia/Data/game/data/stats/shop/multisell/normal/2027.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><list xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance" allowAugmentedItems="false" allowElementalItems="false" keepEnchant="false" ns0:noNamespaceSchemaLocation="../../../../xsd/multisell.xsd" showAll="true" taxFree="true">

	<item>
		<ingredient count="3997000" id="57"/>		
		<production count="1" id="36187"/>		
	</item>
	<item>
		<ingredient count="11941000" id="57"/>		
		<production count="1" id="36188"/>		
	</item>
	<item>
		<ingredient count="1999000" id="57"/>		
		<production count="1" id="36189"/>		
	</item>
	<item>
		<ingredient count="5970000" id="57"/>		
		<production count="1" id="36190"/>		
	</item>
</list>
