=== BloodyDawn/Ertheia/Data/game/data/xsd/NpcData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list" type="listType"/>
	<xs:complexType name="teach_classesType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="minionsType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="setType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="optional"/>
				<xs:attribute type="xs:string" name="value" use="optional"/>
				<xs:attribute type="xs:string" name="id" use="optional"/>
				<xs:attribute type="xs:string" name="level" use="optional"/>
				<xs:attribute type="xs:string" name="amount_min" use="optional"/>
				<xs:attribute type="xs:string" name="amount_max" use="optional"/>
				<xs:attribute type="xs:string" name="x" use="optional"/>
				<xs:attribute type="xs:string" name="y" use="optional"/>
				<xs:attribute type="xs:string" name="z" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence>
			<xs:element type="npcType" name="npc" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="npcType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="ai_paramsType" name="ai_params" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="skillsType" name="skills" minOccurs="0"/>
			<xs:element type="doorsType" name="doors" minOccurs="0"/>
			<xs:element type="teleportPositionsType" name="teleportPositions" minOccurs="0"/>
			<xs:element type="teach_classesType" name="teach_classes" minOccurs="0"/>
			<xs:element type="minionsType" name="minions" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="optional"/>
		<xs:attribute type="xs:string" name="displayId" use="optional"/>
		<xs:attribute type="xs:string" name="name" use="optional"/>
		<xs:attribute type="xs:string" name="title" use="optional"/>
		<xs:attribute type="xs:string" name="server_name" use="optional"/>
	</xs:complexType>
	<xs:complexType name="teleportPositionsType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="doorsType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ai_paramsType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="skillsType">
		<xs:sequence>
			<xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== BloodyDawn/Ertheia/Data/game/custom/npc/npc_farm_zone.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<list xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance" ns0:noNamespaceSchemaLocation="../../data/xsd/NpcData.xsd">
    <npc id="60400" displayId="25857" name="Страшный Монстр" server_name="embryo_fallen_knight" title="Устрашающий">
        <set name="server_side_name" value="true"/>
        <set name="type" value="L2Monster"/>
        <set name="sex" value="male"/>
        <set name="level" value="95"/>
        <set name="exp" value="22010170"/>
        <set name="sp" value="531658"/>
        <set name="org_hp" value="960294"/>
        <set name="org_mp" value="22058"/>
        <set name="org_hp_regen" value="8.5"/>
        <set name="org_mp_regen" value="3"/>
        <set name="base_physical_attack" value="8371"/>
        <set name="base_magic_attack" value="663"/>
        <set name="base_defend" value="341"/>
        <set name="base_magic_defend" value="250"/>
        <set name="base_attack_speed" value="253"/>
        <set name="base_attack_range" value="40"/>
        <set name="base_critical" value="4"/>
        <set name="ground_high" value="120"/>
        <set name="ground_low" value="30"/>
        <set name="str" value="89"/>
        <set name="con" value="75"/>
        <set name="dex" value="42"/>
        <set name="int" value="79"/>
        <set name="wit" value="66"/>
        <set name="men" value="10"/>
        <set name="collision_radius" value="24"/>
        <set name="collision_height" value="45"/>
        <set name="baseFireRes" value="260"/>
        <set name="baseWaterRes" value="260"/>
        <set name="baseWindRes" value="260"/>
        <set name="baseEarthRes" value="260"/>
        <set name="baseDivineRes" value="260"/>
        <set name="baseDarkRes" value="260"/>
        <ai_params>
            <set name="ai_type" value="fighter"/>
        </ai_params>
        <skills>
            <set id="14521" level="1"/>
        </skills>
    </npc>

    <npc id="60401" displayId="25858" name="Страшный Монстр" server_name="embryo_fallen_templer" title="Командир">
        <set name="type" value="L2Monster"/>
        <set name="sex" value="male"/>
        <set name="level" value="98"/>
        <set name="exp" value="52010170"/>
        <set name="sp" value="531658"/>
        <set name="org_hp" value="1660294"/>
        <set name="org_mp" value="33087"/>
        <set name="org_hp_regen" value="8.5"/>
        <set name="org_mp_regen" value="3"/>
        <set name="base_physical_attack" value="10371"/>
        <set name="base_magic_attack" value="663"/>
        <set name="base_defend" value="341"/>
        <set name="base_magic_defend" value="250"/>
        <set name="base_attack_speed" value="253"/>
        <set name="base_attack_range" value="40"/>
        <set name="base_critical" value="4"/>
        <set name="ground_high" value="120"/>
        <set name="ground_low" value="30"/>
        <set name="str" value="89"/>
        <set name="con" value="75"/>
        <set name="dex" value="42"/>
        <set name="int" value="79"/>
        <set name="wit" value="66"/>
        <set name="men" value="10"/>
        <set name="collision_radius" value="18"/>
        <set name="collision_height" value="39"/>
        <set name="baseFireRes" value="260"/>
        <set name="baseWaterRes" value="260"/>
        <set name="baseWindRes" value="260"/>
        <set name="baseEarthRes" value="260"/>
        <set name="baseDivineRes" value="260"/>
        <set name="baseDarkRes" value="260"/>
        <ai_params>
            <set name="ai_type" value="fighter"/>
        </ai_params>
        <skills>
            <set id="14194" level="1"/>
        </skills>
    </npc>
</list>
