=== BloodyDawn/Ertheia/Data/game/data/xsd/OptionData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list" type="listType"/>
	<xs:complexType name="addType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="order" use="optional"/>
				<xs:attribute type="xs:string" name="stat" use="optional"/>
				<xs:attribute type="xs:string" name="val" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="optionDataType">
		<xs:sequence>
			<xs:element type="forType" name="for" minOccurs="0"/>
			<xs:element type="skillsType" name="skills" minOccurs="0">
			</xs:element>
			<xs:element type="triggersType" name="triggers" minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:integer" name="id" use="optional"/>
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence>
			<xs:element type="optionDataType" name="optionData" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="forType">
		<xs:sequence>
			<xs:element type="addType" name="add">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="skillType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:integer" name="id" use="optional"/>
				<xs:attribute type="xs:integer" name="level" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="triggersType">
		<xs:sequence>
			<xs:element type="triggerType" name="trigger">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="triggerType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:integer" name="id" use="optional"/>
				<xs:attribute type="xs:integer" name="level" use="optional"/>
				<xs:attribute type="xs:string" name="type" use="optional"/>
				<xs:attribute type="xs:string" name="chance" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="skillsType" mixed="true">
		<xs:sequence>
			<xs:element type="skillType" name="skill" minOccurs="0">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== BloodyDawn/Ertheia/Data/game/data/stats/items/OptionData/10200-10299.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/OptionData.xsd">
	<optionData id="10200">
		<for>

			<add order="0x60" stat="regHp" val="0.51948"/>
		</for>
	</optionData>
	<optionData id="10201">
		<for>

			<add order="0x60" stat="regMp" val="0.224712"/>
		</for>
	</optionData>
	<optionData id="10202">
		<for>

			<add order="0x60" stat="regCp" val="0.51948"/>
		</for>
	</optionData>
	<optionData id="10203">
		<for>

			<add order="0x60" stat="ratePhysicalEvas" val="1.494696"/>
		</for>
	</optionData>
	<optionData id="10204">
		<for>

			<add order="0x60" stat="accPhysical" val="1.494696"/>
		</for>
	</optionData>
	<optionData id="10205">
		<for>

			<add order="0x60" stat="pCritRate" val="16.184568288"/>
		</for>
	</optionData>
	<optionData id="10206">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="mDef" val="8.964"/>
		</for>
	</optionData>
	<optionData id="10207">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="maxHp" val="44.154"/>
		</for>
	</optionData>
	<optionData id="10208">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="maxMp" val="13.914"/>
		</for>
	</optionData>
	<optionData id="10209">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="maxCp" val="60.975"/>
		</for>
	</optionData>
	<optionData id="10210">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="pAtk" val="5.364"/>
		</for>
	</optionData>
	<optionData id="10211">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="mAtk" val="6.156"/>
		</for>
	</optionData>
	<optionData id="10212">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="regHp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10213">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="regMp" val="0.112356"/>
		</for>
	</optionData>
	<optionData id="10214">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="regCp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10215">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="ratePhysicalEvas" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10216">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="accPhysical" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10217">
		<for>

			<add order="0x60" stat="pDef" val="11.142"/>
			<add order="0x60" stat="pCritRate" val="8.092284144"/>
		</for>
	</optionData>
	<optionData id="10218">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="maxHp" val="44.154"/>
		</for>
	</optionData>
	<optionData id="10219">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="maxMp" val="13.914"/>
		</for>
	</optionData>
	<optionData id="10220">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="maxCp" val="60.975"/>
		</for>
	</optionData>
	<optionData id="10221">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="pAtk" val="5.364"/>
		</for>
	</optionData>
	<optionData id="10222">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="mAtk" val="6.156"/>
		</for>
	</optionData>
	<optionData id="10223">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="regHp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10224">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="regMp" val="0.112356"/>
		</for>
	</optionData>
	<optionData id="10225">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="regCp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10226">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="ratePhysicalEvas" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10227">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="accPhysical" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10228">
		<for>

			<add order="0x60" stat="mDef" val="8.964"/>
			<add order="0x60" stat="pCritRate" val="8.092284144"/>
		</for>
	</optionData>
	<optionData id="10229">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="maxMp" val="13.914"/>
		</for>
	</optionData>
	<optionData id="10230">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="maxCp" val="60.975"/>
		</for>
	</optionData>
	<optionData id="10231">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="pAtk" val="5.364"/>
		</for>
	</optionData>
	<optionData id="10232">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="mAtk" val="6.156"/>
		</for>
	</optionData>
	<optionData id="10233">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="regHp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10234">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="regMp" val="0.112356"/>
		</for>
	</optionData>
	<optionData id="10235">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="regCp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10236">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="ratePhysicalEvas" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10237">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="accPhysical" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10238">
		<for>

			<add order="0x60" stat="maxHp" val="44.154"/>
			<add order="0x60" stat="pCritRate" val="8.092284144"/>
		</for>
	</optionData>
	<optionData id="10239">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="maxCp" val="60.975"/>
		</for>
	</optionData>
	<optionData id="10240">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="pAtk" val="5.364"/>
		</for>
	</optionData>
	<optionData id="10241">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="mAtk" val="6.156"/>
		</for>
	</optionData>
	<optionData id="10242">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="regHp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10243">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="regMp" val="0.112356"/>
		</for>
	</optionData>
	<optionData id="10244">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="regCp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10245">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="ratePhysicalEvas" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10246">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="accPhysical" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10247">
		<for>

			<add order="0x60" stat="maxMp" val="13.914"/>
			<add order="0x60" stat="pCritRate" val="8.092284144"/>
		</for>
	</optionData>
	<optionData id="10248">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="pAtk" val="5.364"/>
		</for>
	</optionData>
	<optionData id="10249">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="mAtk" val="6.156"/>
		</for>
	</optionData>
	<optionData id="10250">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="regHp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10251">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="regMp" val="0.112356"/>
		</for>
	</optionData>
	<optionData id="10252">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="regCp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10253">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="ratePhysicalEvas" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10254">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="accPhysical" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10255">
		<for>

			<add order="0x60" stat="maxCp" val="60.975"/>
			<add order="0x60" stat="pCritRate" val="8.092284144"/>
		</for>
	</optionData>
	<optionData id="10256">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="mAtk" val="6.156"/>
		</for>
	</optionData>
	<optionData id="10257">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="regHp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10258">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="regMp" val="0.112356"/>
		</for>
	</optionData>
	<optionData id="10259">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="regCp" val="0.25974"/>
		</for>
	</optionData>
	<optionData id="10260">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="ratePhysicalEvas" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10261">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="accPhysical" val="0.747348"/>
		</for>
	</optionData>
	<optionData id="10262">
		<for>

			<add order="0x60" stat="pAtk" val="5.364"/>
			<add order="0x60" stat="pCritRate" val="8.092284144"/>
		</for>
	</optionData>
	<optionData id="10263">
		<for>

			<add order="0x60" stat="mAtk" val="6.156"/>
